services:
  db:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./backend/init.js:/docker-entrypoint-initdb.d/init.js

  init:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: python init.py

  app:
    build: ./backend
    restart: on-failure
    volumes:
      - ./backend:/app
      - myimage:/app/static/images
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./app.py
          target: /app/app.py

volumes:
  myimage:
